name: Run the workflow

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "jakubbbdev/github-sync@master"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}